# Generated by Django 4.1.3 on 2022-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profuct_size',
            new_name='product_size',
        ),
    ]
