# Generated by Django 4.1.3 on 2022-11-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_addcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='wishlist',
        ),
    ]
