# Generated by Django 4.1.3 on 2022-11-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_addcart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addcart',
            name='product_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='addcart',
            name='total_price',
            field=models.BooleanField(default=False),
        ),
    ]
